name: Testing checkout
os: workflow_dispatch
jobs:
    files:
        runs-on: ubuntu-latest
        steps:
            -name: Git checkout
             uses: actions/checkout@v5
            -name: Display data in file
             run: cat devops.txt
            -name: display Date
             run: date
