name: Repo Vars and Secrets Example

on:
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: Show repository variable
        run: echo "Company is ${{ vars.COMPANY }}"

      - name: Use secret key
        env:
          KEY: ${{ secrets.API_KEY }}
        run: |
          echo "Secret key received"
          echo "$KEY"   # Will be masked in logs