name: Step level Example
on: workflow_dispatch
jobs:
    demo:
        runs-on: ubuntu-latest
        steps:
            demo:
              -name: sample env 
              
            env:
                    city: Hyderabad
                    name: Siva
            run: |
                   echo: "city is $city"
                   echo: "name is $name"
              -name: next step
            run: 
                echo: "city is $city and name is $name"
                

