name: Step level Example

on:
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: Sample env
        env:
          CITY: Hyderabad
          NAME: Siva
        run: |
          echo "City is $CITY"
          echo "Name is $NAME"

      - name: Next step
        run: |
          echo "City is $CITY and Name is $NAME"