name: testing the workflow

on: push

jobs: 
    test-job:
        runs-on: ubuntu-latest
        steps:
            - name: Display date
              run: date
            - name: print Shiva
              run: echo "Shiva"



